### ISSUE TITLE
expecting a more detailed guide to get start....the path issue ...

### ISSUE THREAD

**Issue by SeekPoint** [deepsemantic/image_captioning#1]
rzai@rzai00:~/prj/image_captioning/examples$ python flickr8K/flickr8K_to_hdf5_data_forward.py 
Traceback (most recent call last):
  File "flickr8K/flickr8K_to_hdf5_data_forward.py", line 23, in <module>
    from coco import COCO
ImportError: No module named coco
rzai@rzai00:~/prj/image_captioning/examples$

**Comment by deepsemantic** [comment]
@loveJasmine Hi, thanks for info, I think you need to download and install coco server first.

**Comment by SeekPoint** [comment]
whcih 'coco server' do you refer? i guess it shoud be https://github.com/tylin/coco-caption, am I right?

**Comment by deepsemantic** [comment]
yes, exactly!
