### ISSUE TITLE
multi_crop

### ISSUE THREAD

**Issue by airocking** [deepsemantic/image_captioning#2]
Thanks for sharing the code!
But there was a question when I was training the model using “.sh” file. I aroused an error as "caffe.TransformationParameter" has no field named "multi_crop" in parsing the  "multi_Bi_LSTM.prototxt", I wonder how you added the field "multi_crop. Is it because the version of CAFFE?

**Comment by deepsemantic** [comment]
Hi thanks for questions.  I am not sure is it the issue of different Caffe Version. I implemented it in "data_transformer.cpp" `  const int crop_size = param_.crop_size();

  const Dtype scale = param_.scale();  

  //const bool do_mirror = param_.mirror() && Rand(2);  

  const bool do_mirror_x = param_.mirror() && Rand(2); // random mirror, true or false

  const bool do_mirror_y = param_.mirror_vertical()&& Rand(2); // random mirror_vertical, false

  const bool multi_crop=param_.multi_crop(); // if set to true, crop image from 1 of 4 corners or center

  const bool multi_scale=param_.multi_scale();// if set to true, resalce image to different scale`

**Comment by SeekPoint** [comment]
does some solved this issue?

**Comment by Atlas-wuu** [comment]
@loveJasmine i have the same problem, have you solved?
