### ISSUE TITLE
Message type "caffe.TransformationParameter" has no field named "multi_crop".

### ISSUE THREAD

**Issue by SeekPoint** [deepsemantic/image_captioning#3]
rzai@rzai00:~/prj/image_captioning$ bash examples/flickr8K/multi_train_Bi_LSTM.sh
I1203 11:15:46.983738 28061 caffe.cpp:217] Using GPUs 0
I1203 11:15:47.008774 28061 caffe.cpp:222] GPU 0: GeForce GTX 1080
I1203 11:15:48.340289 28061 solver.cpp:48] Initializing solver from parameters: 
test_iter: 50
test_interval: 2000
base_lr: 0.01
display: 50
max_iter: 25000
lr_policy: "step"
gamma: 0.1
momentum: 0.9
weight_decay: 0.0005
stepsize: 10000
snapshot: 1000
snapshot_prefix: "./examples/flickr8K/multi_Bi_LSTM_trained_models/multi_Bi_LSTM"
solver_mode: GPU
device_id: 0
random_seed: 1701
net: "./examples/flickr8K/multi_Bi_LSTM.prototxt"
train_state {
  level: 0
  stage: ""
}
average_loss: 100
clip_gradients: 10
I1203 11:15:48.340517 28061 solver.cpp:91] Creating training net from net file: ./examples/flickr8K/multi_Bi_LSTM.prototxt
[libprotobuf ERROR google/protobuf/text_format.cc:245] Error parsing text-format caffe.NetParameter: 24:15: Message type "caffe.TransformationParameter" has no field named "multi_crop".
F1203 11:15:48.340638 28061 upgrade_proto.cpp:88] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: ./examples/flickr8K/multi_Bi_LSTM.prototxt
*** Check failure stack trace: ***
    @     0x7f28b9064daa  (unknown)
    @     0x7f28b9064ce4  (unknown)
    @     0x7f28b90646e6  (unknown)
    @     0x7f28b9067687  (unknown)
    @     0x7f28b97a8f2e  caffe::ReadNetParamsFromTextFileOrDie()
    @     0x7f28b9798bcb  caffe::Solver<>::InitTrainNet()
    @     0x7f28b9799c9c  caffe::Solver<>::Init()
    @     0x7f28b9799fca  caffe::Solver<>::Solver()
    @     0x7f28b9683253  caffe::Creator_SGDSolver<>()
    @           0x40f0fe  caffe::SolverRegistry<>::CreateSolver()
    @           0x408134  train()
    @           0x405b3c  main
    @     0x7f28b8070f45  (unknown)
    @           0x4063ab  (unknown)
    @              (nil)  (unknown)
examples/flickr8K/multi_train_Bi_LSTM.sh: line 10: 28061 Aborted                 (core dumped) $CAFFE/build/tools/caffe train -solver ./examples/flickr8K/multi_Bi_LSTM_solver.prototxt -weights $WEIGHTS -gpu $GPU_ID
rzai@rzai00:~/prj/image_captioning$ ll examples/flickr8K/multi_Bi_LSTM.prototxt
-rw-rw-r-- 1 rzai rzai 10634 10月 24 09:39 examples/flickr8K/multi_Bi_LSTM.prototxt
rzai@rzai00:~/prj/image_captioning$

**Comment by deepsemantic** [comment]
Hi, please refer to issue #2

**Comment by SeekPoint** [comment]
which version of protobuf do you use? @deepsemantic

**Comment by deepsemantic** [comment]
I am using 2.5.0 version
