### ISSUE TITLE
might I need addtional something?

### ISSUE THREAD

**Issue by hengliusky** [deepsemantic/image_captioning#6]
tools/mask.py", line 3, in <module>
    import pycocotools._mask as _mask
ImportError: No module named pycocotools._mask
hengliu@Armari1:/storage/hengliu/image_captionin
do I need to install some additional thing to make flickr8K_to_hdf5_data_forward.py to  work?
Hope you can help me quickly!

**Comment by deepsemantic** [comment]
It seems like you didn't install evaluation sever correctly, please follow the instruction in "data/coco/README.md"  to fix this.

**Comment by hengliusky** [comment]
Thanks! But I searched my 'data' folder.  only found a file 'README.md' in 'data/coco/coco-caption-eval' . I opened the file and it is description on 'Evaluation codes for MS COCO'. Then I downloaded the 'coco-caption-master' from github and replace the folder 'coco/caption-eval' with the contents from 'coco-caption-master'. unfortunately, the error is the same:
-----------------------------------
 File "flickr8K_to_hdf5_data_forward.py", line 23, in <module>
    from coco import COCO
  File "/storage/hengliu/image_captioning-master/data/coco/coco/PythonAPI/pycocotools/coco.py", line 58, in <module>
    import mask
  File "/storage/hengliu/image_captioning-master/data/coco/coco/PythonAPI/pycocotools/mask.py", line 3, in <module>
    import pycocotools._mask as _mask
ImportError: No module named pycocotools._mask
--------------------------------------
And I have updated all original paths in 'flickr8K_to_hdf5_data_forward.py':
---------------------------------------
COCO_PATH = '/home/chengwang/workspace/caffe-recurrent/data/coco/coco'
DATA_PATH = '/data/cheng/flickr8K'
COCO_TOOL_PATH = '%s/PythonAPI/pycocotools' % COCO_PATH
COCO_IMAGE_ROOT = '%s/images' % DATA_PATH
IMAGE_CAPTION='%s/texts/Flickr8k.lemma.token.txt'% DATA_PATH
CAPTION_SPLIT='/home/chengwang/workspace/caffe-recurrent/data/flickr8K/texts/F
----------------------------
to my paths in my machine.

Hope a clear guide on make it run!

**Comment by hengliusky** [comment]
could you release a well trained model for my test?

**Comment by deepsemantic** [comment]
I forgot to upload that README.md file before. I did it two days again, please check it again.

**Comment by hengliusky** [comment]
Thanks. I have taken a look at the README. But where to find 'download_tools.sh' and other scripts you mentioned?

**Comment by deepsemantic** [comment]
Please refer to  https://github.com/tylin/coco-caption

**Comment by hengliusky** [comment]
Ha, also cannot find the 'download_tools.sh' in the link given from you.

**Comment by deepsemantic** [comment]
If you have downloaded this repo, please go to the step 2 of "coco/README.md", try following commands
"cd coco/PythonAPI 
python setup.py install "

**Comment by hengliusky** [comment]
Thanks for your reply. Yest I have downloaded the repo.
after I installed cython and copy some cco tools.when we run python setup.py install, the new error is:

building 'pycocotools._mask' extension
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I../MatlabAPI/private -I/usr/include/python2.7 -c pycocotools/_mask.c -o build/temp.linux-x86_64-2.7/pycocotools/_mask.o -Wno-cpp -Wno-unused-function -std=c99
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I../MatlabAPI/private -I/usr/include/python2.7 -c ../MatlabAPI/private/maskApi.c -o build/temp.linux-x86_64-2.7/../MatlabAPI/private/maskApi.o -Wno-cpp -Wno-unused-function -std=c99
x86_64-linux-gnu-gcc: error: ../MatlabAPI/private/maskApi.c: No such file or directory
x86_64-linux-gnu-gcc: fatal error: no input files
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 4

However, the maskApi.c has been put in the corresponding path.

**Comment by deepsemantic** [comment]
Then I have no idea about this, I didn't have the same issue.

**Comment by docdok** [comment]
please see this:  https://github.com/LisaAnne/lisa-caffe-public/tree/lstm_video_deploy/data
