### ISSUE TITLE
Out of Memory

### ISSUE THREAD

**Issue by usmanxia** [deepsemantic/image_captioning#8]
Can you please share the minimum hardware requirements for the code to run? I have Nvidia 1060 with 6GB RAM and it gives me out of memory exception "Check failed: error == cudaSuccess (2 vs. 0)  out of memory".
Regards

**Comment by deepsemantic** [comment]
I am not sure about the minimum hardware, I think you can follow the official info here: [http://caffe.berkeleyvision.org/installation.html#hardware](url) . You can also reduce batch size, and use smaller visual model for image feature extraction. 6G should be enough with reduced batch size

**Comment by usmanxia** [comment]
Thank you for apt response. Yes I have reduced the batch size to 50 and it's stable at 4 GB.

Thanks again.
